## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999
sudo: false
addons:
    apt_packages:
    - gfortran
script:
  - julia -e 'Pkg.clone("https://github.com/odow/SDDP.jl.git")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SDDiP"); Pkg.test("SDDiP"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SDDiP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
